// Code generated by "stringer -type=Flag"; DO NOT EDIT.

package tel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PreserveNewline-1]
	_ = x[PreserveComment-2]
	_ = x[ExitOnError-4]
	_ = x[HideErrors-8]
	_ = x[ReduceAlloc-16]
	_ = x[FlagNoNativeElement-32]
	_ = x[FlagNoBuiltinType-64]
}

const (
	_Flag_name_0 = "PreserveNewlinePreserveComment"
	_Flag_name_1 = "ExitOnError"
	_Flag_name_2 = "HideErrors"
	_Flag_name_3 = "ReduceAlloc"
	_Flag_name_4 = "FlagNoNativeElement"
	_Flag_name_5 = "FlagNoBuiltinType"
)

var (
	_Flag_index_0 = [...]uint8{0, 15, 30}
)

func (i Flag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Flag_name_0[_Flag_index_0[i]:_Flag_index_0[i+1]]
	case i == 4:
		return _Flag_name_1
	case i == 8:
		return _Flag_name_2
	case i == 16:
		return _Flag_name_3
	case i == 32:
		return _Flag_name_4
	case i == 64:
		return _Flag_name_5
	default:
		return "Flag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
