// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[BracketOpen-1]
	_ = x[BracketClose-2]
	_ = x[ParenOpen-3]
	_ = x[ParenClose-4]
	_ = x[BraceOpen-5]
	_ = x[BraceClose-6]
	_ = x[Comma-7]
	_ = x[Colon-8]
	_ = x[BSlash-9]
	_ = x[Dot-10]
	_ = x[Hyphen-11]
	_ = x[Hash-12]
	_ = x[Package-13]
	_ = x[Import-14]
	_ = x[Using-15]
	_ = x[Component-16]
	_ = x[Document-17]
	_ = x[If-18]
	_ = x[Cond-19]
	_ = x[Enum-20]
	_ = x[Ident-21]
	_ = x[_literalBegin-22]
	_ = x[_constantBegin-23]
	_ = x[True-24]
	_ = x[False-25]
	_ = x[String-26]
	_ = x[Number-27]
	_ = x[_constantEnd-28]
	_ = x[StringLine-29]
	_ = x[StringTempl-30]
	_ = x[StringLineTempl-31]
	_ = x[_literalEnd-32]
	_ = x[Newline-33]
	_ = x[Comment-34]
}

const _Kind_name = "InvalidBracketOpenBracketCloseParenOpenParenCloseBraceOpenBraceCloseCommaColonBSlashDotHyphenHashPackageImportUsingComponentDocumentIfCondEnumIdent_literalBegin_constantBeginTrueFalseStringNumber_constantEndStringLineStringTemplStringLineTempl_literalEndNewlineComment"

var _Kind_index = [...]uint16{0, 7, 18, 30, 39, 49, 58, 68, 73, 78, 84, 87, 93, 97, 104, 110, 115, 124, 132, 134, 138, 142, 147, 160, 174, 178, 183, 189, 195, 207, 217, 228, 243, 254, 261, 268}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
