[[language]]
name = "grammar"
scope = "source.grammar"
injection-regex = "grammar"
file-types = ["grammar"]
comment-tokens = "//"
indent = { tab-width = 2, unit = "  " }
roots = ["token.grammar", "ast.grammar"]

[[language]]
name = "teml"
scope = "source.teml"
injection-regex = "teml"
file-types = ["teml", "tel"]
comment-tokens = ";"
indent = { tab-width = 2, unit = "  " }
roots = ["teml.mod", "tel.mod"]

[[language]]
name = "teml"
scope = "source.teml"
injection-regex = "tel"
file-types = ["tel"]
comment-tokens = ";"
indent = { tab-width = 2, unit = "  " }
roots = ["tel.mod"]

[[grammar]]
name = "grammar"
source = { path = "/home/hnyehamene/.local/tree-sitter/tree-sitter-grammar" }

[[grammar]]
name = "teml"
source = { path = "/home/hnyehamene/.local/tree-sitter/tree-sitter-teml" }

[[grammar]]
name = "tel"
source = { path = "/home/hnyehamene/.local/tree-sitter/tree-sitter-teml" }
