// Code generated by "stringer -type=Bool"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[False-0]
	_ = x[True-1]
}

const _Bool_name = "FalseTrue"

var _Bool_index = [...]uint8{0, 5, 9}

func (i Bool) String() string {
	if i >= Bool(len(_Bool_index)-1) {
		return "Bool(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Bool_name[_Bool_index[i]:_Bool_index[i+1]]
}
