// Code generated by "stringer -type=EntityKind"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EntityInvalid-0]
	_ = x[EntityBuiltin-1]
	_ = x[EntityModule-2]
	_ = x[EntityPackage-3]
	_ = x[EntityType-4]
	_ = x[EntityVar-5]
}

const _EntityKind_name = "EntityInvalidEntityBuiltinEntityModuleEntityPackageEntityTypeEntityVar"

var _EntityKind_index = [...]uint8{0, 13, 26, 38, 51, 61, 70}

func (i EntityKind) String() string {
	if i < 0 || i >= EntityKind(len(_EntityKind_index)-1) {
		return "EntityKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntityKind_name[_EntityKind_index[i]:_EntityKind_index[i+1]]
}
