// Code generated by "stringer -type=Error -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUndeclared-0]
	_ = x[ErrUnbound-1]
	_ = x[ErrDuplicate-2]
	_ = x[ErrUndeclaredNamespace-3]
	_ = x[ErrRecursiveDefinition-4]
	_ = x[ErrInvalidEnumConstant-5]
	_ = x[ErrUndeclaredType-6]
	_ = x[ErrNotObject-7]
	_ = x[ErrUnexpectedChildren-8]
	_ = x[ErrUnexpectedAttribute-9]
	_ = x[ErrUnexpectedParameter-10]
	_ = x[ErrInvalidElementTag-11]
	_ = x[ErrUnexpectedParameterInNativeElement-12]
	_ = x[ErrUnexpectedParameterInPropertyElement-13]
	_ = x[ErrMismatchType-14]
	_ = x[ErrMismatchPackageName-15]
	_ = x[ErrMismatchEnumConstantType-16]
	_ = x[ErrMismatchName-17]
	_ = x[ErrMismatchNamespace-18]
	_ = x[ErrDuplicateParameter-19]
	_ = x[ErrMissingParameter-20]
	_ = x[ErrUndeclaredParameter-21]
	_ = x[ErrInvalidFieldType-22]
	_ = x[ErrNotType-23]
	_ = x[ErrNotBool-24]
	_ = x[ErrNotEnum-25]
	_ = x[ErrGeneric-26]
}

const _Error_name = "UndeclaredUnboundDuplicateVarUndeclaredNamespaceRecursiveDefinitionInvalidEnumConstantUndeclaredTypeNotObjectUnexpectedChildrenUnexpectedAttributeUnexpectedParameterInvalidElementTagUnexpectedParameterInNativeElementUnexpectedParameterInPropertyElementMismatchTypeMismatchPackageNameMismatchEnumConstantTypeMismatchNameMismatchNamespaceDuplicateParameterMissingParameterMissingUndeclaredParameterInvalidFieldTypeNotTypeNotBoolNotEnumGeneric"

var _Error_index = [...]uint16{0, 10, 17, 29, 48, 67, 86, 100, 109, 127, 146, 165, 182, 216, 252, 264, 283, 307, 319, 336, 354, 370, 396, 412, 419, 426, 433, 440}

func (i Error) String() string {
	if i < 0 || i >= Error(len(_Error_index)-1) {
		return "Error(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Error_name[_Error_index[i]:_Error_index[i+1]]
}
