package ast

// HTMLElementType represents a native HTML element.
type HTMLElementType struct {
	Tag                string
	RequiredAttributes []string
	SelfClosing        bool
}

// NativeHTMLElements is a slice of all native HTML elements.
var NativeHTMLElements = []HTMLElementType{
	{Tag: "a", RequiredAttributes: []string{"href"}},
	{Tag: "abbr"},
	{Tag: "acronym"},
	{Tag: "address"},
	{Tag: "applet"},
	{Tag: "area", RequiredAttributes: []string{"alt", "coords", "href", "shape"}},
	{Tag: "article"},
	{Tag: "aside"},
	{Tag: "audio", RequiredAttributes: []string{"src"}},
	{Tag: "b"},
	{Tag: "base", RequiredAttributes: []string{"href"}},
	{Tag: "basefont"},
	{Tag: "bdi"},
	{Tag: "bdo"},
	{Tag: "bgsound"},
	{Tag: "big"},
	{Tag: "blink"},
	{Tag: "blockquote"},
	{Tag: "body"},
	{Tag: "br", SelfClosing: true},
	{Tag: "button"},
	{Tag: "canvas"},
	{Tag: "caption"},
	{Tag: "center"},
	{Tag: "cite"},
	{Tag: "code"},
	{Tag: "col"},
	{Tag: "colgroup"},
	{Tag: "data", RequiredAttributes: []string{"value"}},
	{Tag: "datalist"},
	{Tag: "dd"},
	{Tag: "del"},
	{Tag: "details"},
	{Tag: "dfn"},
	{Tag: "dialog"},
	{Tag: "dir"},
	{Tag: "div"},
	{Tag: "dl"},
	{Tag: "dt"},
	{Tag: "em"},
	{Tag: "embed", RequiredAttributes: []string{"src", "type"}},
	{Tag: "fieldset"},
	{Tag: "figcaption"},
	{Tag: "figure"},
	{Tag: "font"},
	{Tag: "footer"},
	{Tag: "form"},
	{Tag: "frame"},
	{Tag: "frameset"},
	{Tag: "h1"},
	{Tag: "h2"},
	{Tag: "h3"},
	{Tag: "h4"},
	{Tag: "h5"},
	{Tag: "h6"},
	{Tag: "head"},
	{Tag: "header"},
	{Tag: "hgroup"},
	{Tag: "hr", SelfClosing: true},
	{Tag: "html"},
	{Tag: "i"},
	{Tag: "iframe", RequiredAttributes: []string{"src"}},
	{Tag: "img", RequiredAttributes: []string{"alt", "src"}, SelfClosing: true},
	{Tag: "input", RequiredAttributes: []string{"type"}, SelfClosing: true},
	{Tag: "ins"},
	{Tag: "kbd"},
	{Tag: "keygen"},
	{Tag: "label", RequiredAttributes: []string{"for"}},
	{Tag: "legend"},
	{Tag: "li"},
	{Tag: "link", RequiredAttributes: []string{"href", "rel"}, SelfClosing: true},
	{Tag: "listing"},
	{Tag: "main"},
	{Tag: "map", RequiredAttributes: []string{"name"}},
	{Tag: "mark"},
	{Tag: "marquee"},
	{Tag: "menu"},
	{Tag: "menuitem"},
	{Tag: "meta", RequiredAttributes: []string{"content"}, SelfClosing: true},
	{Tag: "meter", RequiredAttributes: []string{"value"}},
	{Tag: "multicol"},
	{Tag: "nav"},
	{Tag: "nextid"},
	{Tag: "nobr"},
	{Tag: "noembed"},
	{Tag: "noframes"},
	{Tag: "noscript"},
	{Tag: "object", RequiredAttributes: []string{"data"}},
	{Tag: "ol"},
	{Tag: "optgroup", RequiredAttributes: []string{"label"}},
	{Tag: "option"},
	{Tag: "output", RequiredAttributes: []string{"for"}},
	{Tag: "p"},
	{Tag: "param", RequiredAttributes: []string{"name", "value"}, SelfClosing: true},
	{Tag: "picture"},
	{Tag: "plaintext"},
	{Tag: "pre"},
	{Tag: "progress", RequiredAttributes: []string{"value"}},
	{Tag: "q"},
	{Tag: "rb"},
	{Tag: "rp"},
	{Tag: "rt"},
	{Tag: "rtc"},
	{Tag: "ruby"},
	{Tag: "s"},
	{Tag: "samp"},
	{Tag: "script", RequiredAttributes: []string{"src"}},
	{Tag: "section"},
	{Tag: "select"},
	{Tag: "slot"},
	{Tag: "small"},
	{Tag: "source", RequiredAttributes: []string{"src"}, SelfClosing: true},
	{Tag: "spacer"},
	{Tag: "span"},
	{Tag: "strike"},
	{Tag: "strong"},
	{Tag: "style"},
	{Tag: "sub"},
	{Tag: "summary"},
	{Tag: "sup"},
	{Tag: "svg"},
	{Tag: "table"},
	{Tag: "tbody"},
	{Tag: "td"},
	{Tag: "template"},
	{Tag: "textarea"},
	{Tag: "tfoot"},
	{Tag: "th"},
	{Tag: "thead"},
	{Tag: "time", RequiredAttributes: []string{"datetime"}},
	{Tag: "title"},
	{Tag: "tr"},
	{Tag: "track", RequiredAttributes: []string{"kind", "src", "srclang"}, SelfClosing: true},
	{Tag: "tt"},
	{Tag: "u"},
	{Tag: "ul"},
	{Tag: "var"},
	{Tag: "video", RequiredAttributes: []string{"src"}},
	{Tag: "wbr", SelfClosing: true},
	{Tag: "xmp"},
}
