// Code generated by "stringer -type=TemplateKind"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TemplateDocument-0]
	_ = x[TemplateComponent-1]
}

const _TemplateKind_name = "TemplateDocumentTemplateComponent"

var _TemplateKind_index = [...]uint8{0, 16, 33}

func (i TemplateKind) String() string {
	if i >= TemplateKind(len(_TemplateKind_index)-1) {
		return "TemplateKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TemplateKind_name[_TemplateKind_index[i]:_TemplateKind_index[i+1]]
}
