// Code generated by "stringer -type=TypeKind"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindInvalid-0]
	_ = x[KindBool-1]
	_ = x[KindNumber-2]
	_ = x[KindString-3]
	_ = x[KindHTML-4]
	_ = x[KindPackage-5]
	_ = x[KindModule-6]
	_ = x[KindTemplate-7]
	_ = x[KindEnum-8]
	_ = x[KindField-9]
}

const _TypeKind_name = "KindInvalidKindBoolKindNumberKindStringKindHTMLKindPackageKindModuleKindTemplateKindEnumKindField"

var _TypeKind_index = [...]uint8{0, 11, 19, 29, 39, 47, 58, 68, 80, 88, 97}

func (i TypeKind) String() string {
	if i < 0 || i >= TypeKind(len(_TypeKind_index)-1) {
		return "TypeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeKind_name[_TypeKind_index[i]:_TypeKind_index[i+1]]
}
